### ISSUE TITLE
rfm object changes `NaN` to `nan`

### ISSUE THREAD

**Issue by SSMK-wq** [sonwanesuresh95/rfm#3]
I have a column in my dataframe (that is not used in rfm analysis) like as below

![image](https://user-images.githubusercontent.com/30723825/167087939-887c5f81-04da-402c-81e5-1ca3cfd1f635.png)

However, once I execute the below code

`r = RFM(df_new, customer_id='unique_key', transaction_date='Date', amount='Revenue')`

the same column `market segment MC` becomes like as below. I verified multiple times. Not sure why is this happening. Is there any shallow copy, deep copy etc stuff happening that is causing change in my input dataframe?

![image](https://user-images.githubusercontent.com/30723825/167088584-d2f1ba3b-4e24-4e4c-a40d-d6a3c7967eaf.png)

**Comment by sonwanesuresh95** [comment]
It is simply because of str() function. It gets NaN values converted to 'nan'. 
Will add a feature in next release to use specified columns for analysis and keep/remove NaN records.
