### ISSUE TITLE
Customers in multiple segments - expected?

### ISSUE THREAD

**Issue by SSMK-wq** [sonwanesuresh95/rfm#4]
I was going through your code and pasting a small section of it

```
 if (r in (4,5)) & (f in (4,5)) & (m in (4,5)):
                classes_append({rec[cust]:'Champions'})
            elif (r in (4,5)) & (f in (1,2)) & (m in (3,4,5)):
                classes_append({rec[cust]:'Promising'})
            elif (r in (3,4,5)) & (f in (3,4,5)) & (m in (3,4,5)):
                classes_append({rec[cust]:'Loyal Accounts'})
```

Based on this definition, a customer who is a Champion will also be put under the `Loyal accounts` category. Am I right? Is this how RFM works as well? I thought each customer will only be in one segment only

So, it is possible that same customer will be present in multiple segment?

**Comment by SSMK-wq** [comment]
@sonwanesuresh95 

by the below table, I understand that `[3.5]` means values from 3 to 4 to 5. So, I was thinking a customer from one segment could be present in another as well? Am I right?

ex: If someone scores 5,5,5, then he will be in both `loyal accounts` and `champions` segment. Am I right?

![image](https://user-images.githubusercontent.com/30723825/170870509-f6992398-280d-47f9-b5f4-35dea2484b09.png)

**Comment by sonwanesuresh95** [comment]
You see there is gradual filtering implemented. Also use of elif reinforces that no other group is attached to a single user attributes.

So, 5,5,5 score will be caught in the champions category first, as it appears before loyal accounts in those if conditions. Once it is categorized as a Champion, use of elif keyword helps it avoid getting caught in the remaining categories.

For more detail about how if-elif-else works, please check out : https://www.programiz.com/python-programming/if-elif-else
